# REVIEW: trigger on "tags/v*"?
trigger: none

strategy:
  matrix:
    linux:
      vmImage: 'ubuntu-latest'
      SL: '/'
    mac:
      vmImage: 'macos-latest'
      SL: '/'
    windows:
      vmImage: 'windows-latest'
      SL: '\'

pool:
  vmImage: $(vmImage)

# Build numbering format -> $(Build.BuildNumber).
#name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  DOTNET_MULTILEVEL_LOOKUP: 1

  # Settings.
  versionSuffix: 'ci-azp.$(Build.BuildNumber)-$(vmImage)'

  artifactsPath: '$(Agent.TempDirectory)$(SL)nuget-packages$(SL)'
  localNuGetFeed: '$(Build.SourcesDirectory)$(SL)__$(SL)nuget-feed$(SL)'

  packProject: 'src$(SL)Abc.Maybe'
  packConfiguration: 'Release'
  packNuGetConfig: 'NuGet.Config'

  cacheProject: 'test$(SL)NuGetCaching'

  testProject: 'test$(SL)Package'
  testConfiguration: 'Debug'
  testNuGetConfig: 'test$(SL)NuGet.Config'

  # Misc ENV variables.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: 'skip'

steps:
  # Setup.
  - task: DotNetCoreCLI@2
    displayName: '.NET Version'
    inputs:
      command: custom
      custom: '--version'

  # Restore (pack).
  - task: DotNetCoreCLI@2
    displayName: 'Restore (pack)'
    inputs:
      command: 'restore'
      projects: '$(packProject)'
      arguments: '-c $(packConfiguration)'
      feedsToUse: config
      nugetConfigPath: '$(packNuGetConfig)'
      verbosityRestore: 'minimal'

  # Build (pack).
  - task: CmdLine@2
    displayName: 'Build (pack)'
    inputs:
      script: |
        dotnet build $(packProject) -c $(packConfiguration) --no-restore /p:VersionSuffix=$(versionSuffix) /p:Retail=true /p:PrintSettings=true

  # Pack.
  - task: CmdLine@2
    displayName: 'Pack'
    inputs:
      script: |
        dotnet pack $(packProject) -c $(packConfiguration) --no-build /p:VersionSuffix=$(versionSuffix) /p:Retail=true --output $(artifactsPath)

  # Publish artifact.
  - task: PublishPipelineArtifact@1
    displayName: 'Publish artifact'
    inputs:
      path: '$(artifactsPath)'
      artifactName: 'NuGet Packages for $(vmImage)'

  # Update local NuGet feed.
  - task: CmdLine@2
    displayName: 'Update local NuGet feed'
    inputs:
      script: |
        dotnet nuget push $(artifactsPath)*.nupkg -s $(localNuGetFeed) --skip-duplicate

  # Update local NuGet cache.
  - task: DotNetCoreCLI@2
    displayName: 'Update local NuGet cache'
    inputs:
      command: 'restore'
      projects: '$(cacheProject)'
      arguments: '/p:AbcVersionSuffix=$(versionSuffix)'
      feedsToUse: config
      nugetConfigPath: '$(testNuGetConfig)'
      verbosityRestore: 'minimal'

  # Restore (test).
  - task: DotNetCoreCLI@2
    displayName: 'Restore (test)'
    inputs:
      command: 'restore'
      projects: '$(testProject)'
      arguments: '-c $(testConfiguration) /p:AbcVersionSuffix=$(versionSuffix)'
      feedsToUse: config
      nugetConfigPath: '$(testNuGetConfig)'
      verbosityRestore: 'minimal'

  # Build (test).
  - task: DotNetCoreCLI@2
    displayName: 'Build (test)'
    inputs:
      command: 'build'
      projects: '$(testProject)'
      arguments: '-c $(testConfiguration) --no-restore /p:AbcVersionSuffix=$(versionSuffix) /p:EnableSourceLink=false'

  # Test.
  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '$(testProject)'
      arguments: '-c $(testConfiguration) --no-build /p:AbcVersionSuffix=$(versionSuffix)'
