
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - .github/*
    - __/*
    - doc/*
    - test/*
    - CHANGELOG
    - LICENSE*
    - README.md

pool:
  vmImage: 'windows-latest'

variables:
  mainSolution: 'Maybe.sln'
  buildConfiguration: 'Release'
  nugetConfig: 'NuGet.config'
  coverletSettings: '.config\coverlet.runsettings'
  # ENV variables.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_MULTILEVEL_LOOKUP: 0
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: 'skip'

steps:
  # Initialize environment.
  - task: DotNetCoreCLI@2
    displayName: 'Print .NET version'
    inputs:
      command: custom
      custom: '--info'

  - task: UseDotNet@2
    displayName: 'Use global.json'
    inputs:
      packageType: sdk
      useGlobalJson: true

  - task: DotNetCoreCLI@2
    displayName: 'Print .NET version'
    inputs:
      command: custom
      custom: '--info'

  # Restore.
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '$(mainSolution)'
      arguments: '-c $(buildConfiguration)'
      feedsToUse: config
      nugetConfigPath: '$(nugetConfig)'
      verbosityRestore: 'normal'

  # Build.
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '$(mainSolution)'
      arguments: '-c $(buildConfiguration) --no-restore /p:PrintSettings=true'

  # Test + Code Coverage.
  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: 'src/Abc.Tests/Abc.Tests.csproj'
      arguments: '-c $(buildConfiguration) --no-build --collect:"XPlat Code Coverage" --settings $(coverletSettings)'
      nobuild: true

  # Process CC results then publish the report.
  - task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
    displayName: 'Process CC'
    inputs:
      reports: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
      targetdir: '$(Agent.TempDirectory)'
      reporttypes: 'Cobertura'

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish CC'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Agent.TempDirectory)/Cobertura.xml'
