trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  DOTNET_MULTILEVEL_LOOKUP: 0

  # Misc ENV variables.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: 'skip'

steps:
  # Setup.
  # DO NOT REMOVE this task.
  # Without it, the next call to dotnet.exe is very slow, don't know why.
  - task: DotNetCoreCLI@2
    displayName: '.NET Version'
    inputs:
      command: custom
      custom: '--version'

  #- task: UseDotNet@2
  #  displayName: 'Setup'
  #  inputs:
  #    packageType: sdk
  #    useGlobalJson: true

  # Restore.
  - task: PowerShell@2
    displayName: 'Restore'
    inputs:
      filePath: 'eng\make.ps1'
      arguments: 'restore -X -NoStandard /p:Retail=true'
      pwsh: true

  # Build.
  - task: PowerShell@2
    displayName: 'Build'
    inputs:
      filePath: 'eng\make.ps1'
      arguments: 'build -X -NoStandard -NoRestore /p:Retail=true /p:VersionSuffix=ci'
      pwsh: true
