
trigger: none

pool:
  vmImage: 'windows-latest'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Print .NET version'
    inputs:
      command: custom
      custom: '--info'

  - pwsh: echo ("`nPowerShell Version = {0}" -f $PSVersionTable.PSVersion)
    displayName: 'Print PS version'
