trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  DOTNET_MULTILEVEL_LOOKUP: 0

  # Misc ENV variables.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: 'skip'

steps:
  # Setup.
  - task: DotNetCoreCLI@2
    displayName: '.NET Version'
    inputs:
      command: custom
      custom: '--version'

  - task: UseDotNet@2
    # DISABLED
    enabled: false
    displayName: 'Setup'
    inputs:
      packageType: sdk
      useGlobalJson: true

  # Restore.
  - task: PowerShell@2
    displayName: 'Restore'
    inputs:
      filePath: 'eng\make.ps1'
      arguments: 'restore -c Release -X -NoStandard'
      pwsh: true

  # Build.
  - task: PowerShell@2
    displayName: 'Build'
    inputs:
      filePath: 'eng\make.ps1'
      arguments: 'build -c Release -X -NoStandard -NoRestore'
      pwsh: true
