trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - .azure/*
    - .config/*
    - .github/*
    - __/*
    - doc/*
    - eng/*
    - test/*
    - CHANGELOG
    - README.md

pool:
  vmImage: 'windows-latest'

variables:
  DOTNET_MULTILEVEL_LOOKUP: 1

  # Settings.
  mainSolution: 'Maybe.sln'
  buildConfiguration: 'Debug'
  coverletSettings: '.config\coverlet.runsettings'
  disable.coverage.autogenerate: true

  # Misc ENV variables.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: 'skip'

steps:
  # Setup.
  # DO NOT REMOVE this task.
  # Without it, the next call to dotnet.exe is very slow, don't know why.
  - task: DotNetCoreCLI@2
    displayName: '.NET Version'
    inputs:
      command: custom
      custom: '--version'

  - task: UseDotNet@2
    # DISABLED
    enabled: false
    displayName: 'Setup'
    inputs:
      packageType: sdk
      useGlobalJson: true
      performMultiLevelLookup: true

  # Restore.
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '$(mainSolution)'
      verbosityRestore: 'normal'

  # Build.
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '$(mainSolution)'
      arguments: '-c $(buildConfiguration) --no-restore'

  # Test & Code Coverage.
  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '$(mainSolution)'
      arguments: '-c $(buildConfiguration) --no-build --collect:"XPlat Code Coverage" --settings $(coverletSettings)'

  - task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
    displayName: 'Process CC'
    inputs:
      reports: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
      targetdir: '$(Agent.TempDirectory)'
      reporttypes: 'Cobertura'

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish CC'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Agent.TempDirectory)/Cobertura.xml'
