
trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  # ENV variables.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_MULTILEVEL_LOOKUP: 0
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: 'skip'

steps:
  # Initialize environment.
  - task: DotNetCoreCLI@2
    displayName: 'Print .NET version'
    inputs:
      command: custom
      custom: '--info'

  - task: UseDotNet@2
    displayName: 'Use global.json'
    inputs:
      packageType: sdk
      useGlobalJson: true

  - task: DotNetCoreCLI@2
    displayName: 'Print .NET version'
    inputs:
      command: custom
      custom: '--info'

  - pwsh: echo ("`nPowerShell Version = {0}" -f $PSVersionTable.PSVersion)
    displayName: 'Print PS version'
