
trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  # ENV variables.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_MULTILEVEL_LOOKUP: 0
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: 'skip'

steps:
  # Initialize.
  - task: UseDotNet@2
    displayName: 'Use global.json'
    inputs:
      packageType: sdk
      useGlobalJson: true

  # Restore.
  - task: PowerShell@2
    displayName: 'Restore'
    inputs:
      filePath: 'eng\make.ps1'
      arguments: '-t restore -Flat -NoStandard /p:Retail=true'
      pwsh: true

  # Build.
  - task: PowerShell@2
    displayName: 'Build'
    inputs:
      filePath: 'eng\make.ps1'
      arguments: '-t build -Flat -NoStandard -NoRestore /p:Retail=true /p:VersionSuffix=ci'
      pwsh: true
