trigger: none

strategy:
  matrix:
    linux:
      vmImage: 'ubuntu-latest'
    mac:
      vmImage: 'macos-latest'
    windows:
      vmImage: 'windows-latest'

pool:
  vmImage: $(vmImage)

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Dot NET'
    inputs:
      command: custom
      custom: '--info'

  - pwsh: echo ("`nPowerShell Version = {0}" -f $PSVersionTable.PSVersion)
    displayName: 'PowerShell'
