
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - .github/*
    - __/*
    - doc/*
    - test/*
    - CHANGELOG
    - LICENSE*
    - README.md

pool:
  vmImage: 'windows-latest'

variables:
  # ENV variables.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_MULTILEVEL_LOOKUP: 1
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: 'skip'

steps:
  # Initialize environment.
  - task: UseDotNet@2
    displayName: 'Use global.json'
    inputs:
      packageType: sdk
      useGlobalJson: true
      performMultiLevelLookup: true

  - task: DotNetCoreCLI@2
    displayName: 'Print .NET version'
    inputs:
      command: custom
      custom: '--info'

  #- pwsh: echo ("`nPowerShell Version = {0}" -f $PSVersionTable.PSVersion)
  #  displayName: 'Print PS version'

  # Restore.
  - task: PowerShell@2
    displayName: 'Restore'
    inputs:
      filePath: 'eng\ci.ps1'
      arguments: 'restore -Family any'
      pwsh: true

  # Build.
  - task: PowerShell@2
    displayName: 'Build'
    inputs:
      filePath: 'eng\ci.ps1'
      arguments: 'build -Family any'
      pwsh: true

  # Test.
  - task: PowerShell@2
    displayName: 'Test for .NET Framework'
    inputs:
      filePath: 'eng\ci.ps1'
      arguments: 'test -Family classic'
      pwsh: true

  - task: PowerShell@2
    displayName: 'Test for .NET Core'
    inputs:
      filePath: 'eng\ci.ps1'
      arguments: 'test -Family core'
      pwsh: true
