
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - .github/*
    - __/*
    - doc/*
    - test/*
    - CHANGELOG
    - LICENSE*
    - README.md

pool:
  vmImage: 'windows-latest'

variables:
  # ENV variables.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_MULTILEVEL_LOOKUP: 0
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: 'skip'

steps:
  # Initialize.
  - task: UseDotNet@2
    displayName: 'Use global.json'
    inputs:
      packageType: sdk
      useGlobalJson: true

  # Restore.
  - task: PowerShell@2
    displayName: 'Restore'
    inputs:
      filePath: 'eng\ci.ps1'
      arguments: 'restore -Family any -All'
      pwsh: true

  # Build.
  - task: PowerShell@2
    displayName: 'Build'
    inputs:
      filePath: 'eng\ci.ps1'
      arguments: 'build -Family any -All'
      pwsh: true
