trigger: none

pool:
  vmImage: 'windows-latest'

# TODO:
# - trigger on "tags/v*"?
# - package version
# - update local NuGet feed -> should use dotnet push
# - packing on Linux/MacOS requires "net461"

# This is the default value, will be available as $(Build.BuildNumber).
name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  DOTNET_MULTILEVEL_LOOKUP: 1

  # Settings.
  versionSuffix: 'ci-azp.$(Build.BuildNumber)'
  #packageVersion: '9.9.9-$(versionSuffix)'

  artifactsPath: '$(Agent.TempDirectory)\nuget-packages\'
  localNuGetFeed: '__\nuget-feed'

  packProject: 'src\Abc.Maybe'
  packConfiguration: 'Release'
  packNuGetConfig: 'NuGet.Config'

  cacheProject: 'test\NuGetCaching'

  testProject: 'test\Package'
  testConfiguration: 'Debug'
  testNuGetConfig: 'test\NuGet.Config'

  # Misc ENV variables.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: 'skip'

steps:
  # Setup.
  - task: DotNetCoreCLI@2
    displayName: '.NET Version'
    inputs:
      command: custom
      custom: '--version'

  # Restore (pack).
  - task: DotNetCoreCLI@2
    displayName: 'Restore (pack)'
    inputs:
      command: 'restore'
      projects: '$(packProject)'
      arguments: '-c $(packConfiguration)'
      feedsToUse: config
      nugetConfigPath: '$(packNuGetConfig)'
      verbosityRestore: 'minimal'

  # Build (pack).
  - task: DotNetCoreCLI@2
    displayName: 'Build (pack)'
    inputs:
      command: custom
      arguments: 'build $(packProject) -c $(packConfiguration) --no-restore /p:VersionSuffix=$(versionSuffix) /p:Retail=true /p:PrintSettings=true'

  # Pack.
  - task: DotNetCoreCLI@2
    displayName: 'Pack'
    inputs:
      command: 'pack'
      packagesToPack: '$(packProject)'
      configurationToPack: '$(packConfiguration)'
      verbosityPack: 'normal'
      packDirectory: '$(artifactsPath)'
      versioningScheme: 'off'
      #versioningScheme: byEnvVar
      #versionEnvVar: packageVersion
      nobuild: true

  # Publish artifact.
  - task: PublishPipelineArtifact@1
    displayName: 'Publish artifact'
    inputs:
      path: '$(artifactsPath)'
      artifactName: 'NuGet Packages'

  # Update local NuGet feed.
  - task: CopyFiles@2
    # DISABLED
    enabled: false
    displayName: 'Update local NuGet feed'
    inputs:
      sourceFolder: '$(artifactsPath)'
      targetFolder: '$(localNuGetFeed)'
      contents: '*.nupkg'

  - task: DotNetCoreCLI@2
    displayName: 'Update local NuGet feed'
    inputs:
      command: custom
      custom: 'nuget push $(artifactsPath)\*.nupkg -s $(localNuGetFeed)'

  # Update local NuGet cache.
  - task: DotNetCoreCLI@2
    displayName: 'Update local NuGet cache'
    inputs:
      command: 'restore'
      projects: '$(cacheProject)'
      arguments: '/p:AbcVersionSuffix=$(versionSuffix)'
      feedsToUse: config
      nugetConfigPath: '$(testNuGetConfig)'
      verbosityRestore: 'minimal'

  # Restore (test).
  - task: DotNetCoreCLI@2
    displayName: 'Restore (test)'
    inputs:
      command: 'restore'
      projects: '$(testProject)'
      arguments: '-c $(testConfiguration) /p:AbcVersionSuffix=$(versionSuffix)'
      feedsToUse: config
      nugetConfigPath: '$(testNuGetConfig)'
      verbosityRestore: 'minimal'

  # Build (test).
  - task: DotNetCoreCLI@2
    displayName: 'Build (test)'
    inputs:
      command: 'build'
      projects: '$(testProject)'
      arguments: '-c $(testConfiguration) --no-restore /p:AbcVersionSuffix=$(versionSuffix) /p:EnableSourceLink=false'

  # Test.
  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '$(testProject)'
      arguments: '-c $(testConfiguration) --no-build /p:AbcVersionSuffix=$(versionSuffix)'
