trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  DOTNET_MULTILEVEL_LOOKUP: 1

  # Settings.
  packProject: 'src\Abc.Maybe'
  packConfiguration: 'Release'
  packNugetConfig: 'NuGet.config'

  cacheProject: 'test\NuGetCaching'

  testProject: 'test\Package'
  testConfiguration: 'Release'
  testNugetConfig: 'test\NuGet.config'

  versionSuffix: 'ci-$(Build.BuildNumber)'
  localFeed: '__\nuget-feed'

  # Misc ENV variables.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: 'skip'

steps:
  # Setup.
  - task: DotNetCoreCLI@2
    displayName: '.NET Version'
    inputs:
      command: custom
      custom: '--version'

  # Restore.
  - task: DotNetCoreCLI@2
    displayName: 'Restore (pack)'
    inputs:
      command: 'restore'
      projects: '$(packProject)'
      arguments: '-c $(packConfiguration)'
      feedsToUse: config
      nugetConfigPath: '$(packNugetConfig)'
      verbosityRestore: 'minimal'

  # Build.
  - task: DotNetCoreCLI@2
    displayName: 'Build (pack)'
    inputs:
      command: 'build'
      projects: '$(packProject)'
      arguments: '-c $(packConfiguration) --no-restore --version-suffix:$(versionSuffix) /p:Retail=true /p:EnableSourceLink=true'

  # Pack.
  - task: DotNetCoreCLI@2
    displayName: 'Pack'
    inputs:
      command: 'pack'
      packagesToPack: '$(packProject)'
      configurationToPack: '$(packConfiguration)'
      verbosityPack: 'normal'
      nobuild: true

  - publish: $(System.ArtifactStagingDirectory)/**/*.nupkg
    artifact: NuGet

  # Update local NuGet cache.
  - task: DotNetCoreCLI@2
    enabled: false
    displayName: 'Update cache'
    inputs:
      command: 'restore'
      projects: '$(cacheProject)'
      arguments: '/p:AbcVersion=0.0.1-$(versionSuffix)'
      feedsToUse: config
      nugetConfigPath: '$(testNugetConfig)'
      verbosityRestore: 'minimal'

  # Restore.
  - task: DotNetCoreCLI@2
    enabled: false
    displayName: 'Restore (test)'
    inputs:
      command: 'restore'
      projects: '$(testProject)'
      arguments: '-c $(testConfiguration) /p:AbcVersion=0.0.1-$(versionSuffix)'
      feedsToUse: config
      nugetConfigPath: '$(testNugetConfig)'
      verbosityRestore: 'minimal'

  # Build.
  - task: DotNetCoreCLI@2
    enabled: false
    displayName: 'Build (test)'
    inputs:
      command: 'build'
      projects: '$(testProject)'
      arguments: '-c $(testConfiguration) --no-restore /p:AbcVersion=0.0.1-$(versionSuffix)'

  # Test.
  - task: DotNetCoreCLI@2
    enabled: false
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '$(testProject)'
      arguments: '-c $(testConfiguration) --no-build /p:AbcVersion=0.0.1-$(versionSuffix)'
