
trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - __/*
    - doc/*
    - eng/*
    - test/*
    - CHANGELOG
    - LICENSE*
    - README.md

pool:
  vmImage: 'windows-latest'

variables:
  mainSolution: 'Maybe.sln'
  buildConfiguration: 'Release'
  #buildTarget: 'netcoreapp3.1'
  nugetConfig: 'NuGet.config'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUGET_XMLDOC_MODE: 'skip'

steps:
  - task: UseDotNet@2
    displayName: 'Use global.json'
    inputs:
      packageType: sdk
      useGlobalJson: true

  - task: DotNetCoreCLI@2
    displayName: 'Print .NET version'
    inputs:
      command: custom
      custom: '--info'

  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '$(mainSolution)'
      feedsToUse: config
      nugetConfigPath: '$(nugetConfig)'
      verbosityRestore: 'normal'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '$(mainSolution)'
      arguments: '-c $(buildConfiguration) --no-restore /p:PrintSettings=true'

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: 'src/Abc.Tests/Abc.Tests.csproj'
      #arguments: '-c $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Include="[Abc.Maybe]*" /p:Exclude="[Abc.Maybe]System.*"'
      arguments: '-c $(buildConfiguration) --collect:"XPlat Code Coverage" --settings coverlet.runsettings'
      nobuild: true

  - task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
    displayName: 'Create CC Report'
    inputs:
      # WARNING: uncomment variables.buildTarget too.
      #reports: 'src/Abc.Tests/coverage.$(buildTarget).cobertura.xml'
      reports: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
      targetdir: '$(Agent.TempDirectory)'
      reporttypes: 'Cobertura'

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish CC Report'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Agent.TempDirectory)/Cobertura.xml'
