
trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - __/*
    - doc/*
    - eng/*
    - test/*
    - CHANGELOG
    - LICENSE*
    - README.md

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: 'Maybe.sln'
      arguments: '-c $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: 'src/Abc.Tests/Abc.Tests.csproj'
      arguments: '-c $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Include="[Abc.Maybe]*" /p:Exclude="[Abc.Maybe]System.*"'
      nobuild: true

  - task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
    displayName: 'Create CC Report'
    inputs:
      reports: 'src/Abc.Tests/coverage.netcoreapp3.1.cobertura.xml'
      targetdir: '__/azure/'
      reporttypes: 'HtmlInline_AzurePipelines;Cobertura'

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish CC Report'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Build.SourcesDirectory)/__/azure/Cobertura.xml'
      reportDirectory: '$(Build.SourcesDirectory)/__/azure/'
