# Not yet activated.
# https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops
trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - doc/*
    - eng/*
    - test/*

pr: none