name: tests

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '__/*'
    - 'doc/*'
    - 'test/*'
    - 'CHANGELOG'
    - 'LICENSE*'
    - 'README.md'
    - 'azure-pipelines*'

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    env:
      DOTNET_NOLOGO: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_XMLDOC_MODE: 'skip'

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Restore
      run: dotnet restore /p:TargetFrameworks=\"netcoreapp3.1;netcoreapp2.1\"
    - name: Build
      run: dotnet build --no-restore /p:TargetFrameworks=\"netcoreapp3.1;netcoreapp2.1\"
    - name: Test
      run: dotnet test --no-build /p:TargetFrameworks=\"netcoreapp3.1;netcoreapp2.1\"
